name: Deno update dependencies 

on:
  workflow_call: # makes this workflow reusable 
    inputs:
      files: # 
        required: true
        description: 'Glob or space-separated list of files to update. Example: `deps.ts main.ts` or `*.ts`.'        
        type: string
      lock-file:
        required: false 
        default: ''
        description: 'Path to deno.lock file if you want to update it'
        type: string
      pr-title: 
        required: false 
        default: 'refactor: update Deno dependencies'
        type: string 
        description: The title of the PR that gets created by workflow 
      pr-base-branch: 
        required: false 
        description: 'Destination branch name for the PR to get merged into. Default: main'
        type: string
        default: main
    secrets:
      github-token:
        description: GitHub token used when creating pull request.
        required: false 

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    # permissions: these will be added by caller 
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Update dependencies
        run: deno run -A https://raw.githubusercontent.com/levibostian/deno-udd/main/main.ts ${{ inputs.files }}
      
      - name: Update or create lock file if exists 
        if: ${{ inputs.lock-file != '' }}
        run: deno cache --reload --lock='${{ inputs.lock-file }}' --lock-write ${{ inputs.files }}
      
      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ inputs.pr-title }}
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd)
          branch: deno-dependency-updates
          delete-branch: true # delete after close PR
          base: ${{ inputs.pr-base-branch }} 
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}